@startuml OnlineStoreInformationSystem

!define ENTITY class

title Domain model class diagram  "Online Store Information System"

ENTITY Order {
  - OrderID
  - OrderDate
  - OrderStatus
  - {PaymentMethod}
  - {DeliveryMethod}
  - {Goods}
  - {PaymentMethod}
  - {ClientAddress}
}

ENTITY Client {
  - ClientID
  - Name
  - Surname
  - DateOfBirth
  - Email
  - Password
  - {ClientAddress}
  - {Order}
}

ENTITY ClientAddress {
  - AddressID
  - Country
  - City
  - PostalCode
  - Street
  - Home
  - Apartment
}

ENTITY PaymentMethod {
  - PaymentMethodID
  - MethodType
}

ENTITY DeliveryMethod {
  - DeliveryMethodID
  - MethodType
}

ENTITY Goods {
  - GoodsID
  - Title
  - Price
  - Category
  - Brand
  - Color
  - Weight
  - Volume
  - QuantityInStock
}

ENTITY PaymentStatus {
  - PaymentStatusID
  - Status
}


Client "1" -- "0..*" Order  
Order "1" -- "1" ClientAddress
Order "1" -- "1..3" PaymentMethod
Order "1" -- "1..2" DeliveryMethod
Order "1" -- "0..*" Goods
Order "1" -- "1" PaymentStatus
Client "1" -- "0..*" ClientAddress

@enduml
