openapi: 3.0.0
info:
  title: TonyStar API
  description: This API is used to interact with the TonyStar backend system.
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
    description: Dev server
paths:
  /clients:
    get:
      summary: Returns a list of clients.
      # description: Optional extended description in CommonMark or HTML.
      tags: 
        - Clients
      operationId: getAllClients
      responses:
        '200':    # status code
          description: Successful response with customer list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clients'
components:
  schemas:
    Client:
      type: object
      required:
       - Name
       - Surname
       - DateOfBirth
       - Email
      properties:
       Name:
        type: string
        example: Anton
       Surname:
        type: string
        example: "Isakov"
       DateOfBirth:
        type: string
        format: 20.11.1982
       Email:
        type: string
        example: electroautomatic@gmail.com
      
    Clients:
      type: array
      items:
        $ref: '#/components/schemas/Client'
